apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/taiseerhussein/gitops-catalog.git
    targetRevision: cust_aap
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
