apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: automation-eda
  namespace: ansible-automation-platform
spec:
  # automation_server_ssl_verify: 'no'
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  no_log: false
  activation_worker:
    replicas: 5
  image_pull_policy: IfNotPresent
  ipv6_disabled: false
  ui:
    replicas: 1
  set_self_labels: true
  api:
    gunicorn_workers: 2
    replicas: 1
  force_drop_db: false
  scheduler:
    replicas: 1
  redis:
    replicas: 1
  automation_server_url: https://aap.apps.alice.lab.uc2.io
  admin_user: admin
  loadbalancer_protocol: http
  default_worker:
    replicas: 2
  worker:
    replicas: 2
