apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators-appset
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/taiseerhussein/gitops-catalog.git
      revision: cust_aap
      directories:
      - path: ansible-automation-platform/operator/overlays/stable-2.5
      - path: ansible-automation-platform/instance/overlays/default
      - path: ansible-automation-platform/hub-instance/overlays/default
      - path: ansible-automation-platform/eda-instance/overlays/default
  template:
    metadata:
      name: '{{index .path.segments 0}}-{{index .path.segments 1}}'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/taiseerhussein/gitops-catalog.git
        targetRevision: cust_aap
        path: '{{.path.path}}'

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        #namespace: ansible-automation-platform
        namespace: openshift-gitops

      # Sync policy
      syncPolicy:
        syncOptions: 
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
